package:
  name: "dynetx"
  version: "0.3.1"

source:
  git_rev: v0.3.1
  git_url: https://github.com/GiulioRossetti/dynetx

requirements:
  host:
    - python
    - setuptools
  build:
    - python
    - setuptools
  run:
    - python>=3.7
    - numpy
    - future
    - tqdm
    - networkx>=2.4
    - decorator

about:
  home: https://github.com/GiulioRossetti/dynetx
  license: BSD-2-Clause
  license_familY: BSD
  license_file: LICENSE
  summary: "Dynamic Network library"

extra:
  recipe-maintainers:
    - GiulioRossetti
